### ISSUE TITLE
differential backup syntax please

### ISSUE THREAD

**Issue by tukoz** [conformal/cyphertite#108]
Hi,
For differential backups the [wiki](https://opensource.conformal.com/wiki/cyphertite_configuration#differential_backups) says

```
$ cyphertite -B 110522_usr_local_bin_1.ct -cvf 110523_usr_local_bin_2.ct /usr/local/bin
```

I have no idea on how to use this example for automation (daily or else) in eg. crontab?

Here's what I have atm before reading some more precision.
$ crontab -l

```
23   13    *    *    *   <path_to/user_incremental.daily>
```

The user_incremental.daily> executable bash script:

```
 ct -E /home/kozaki/.cyphertite/exclude -cHf <md_filename>1.ct
```

And ~/.cyphertite/cyphertite.conf:

```
ctfile_remote_auto_incremental  = 1                                                
ctfile_differential_allfiles    = 1                                                
ctfile_max_incrementals = 7                                                        
ctfile_cull_keep_days = 30
```

**Comment by SirHumphreyAppleby** [comment]
If doing automatic incremental backups, you use the same command you would use for creating a full backup. Cyphertite will create a full backup initially, then ctfile_max_incrementals incremental backups, before doing another full backup.

**Comment by tukoz** [comment]
Aha thank you sir!
Maybe the wiki would gain clarity with this clarification.
This way, backups ie ctfiles older than `ctfile_cull_keep_days` will be removed, unless their content is still referenced in newer (less than 30 days in this case) ctfiles. Correct?
