### ISSUE TITLE
Set up multiple machine backups

### ISSUE THREAD

**Issue by tukoz** [conformal/cyphertite#109]
The [wiki](https://opensource.conformal.com/wiki/cyphertite_configuration#multiple_machines) says:

> **multiple machines**
> 
> Having configured and tested cyphertite running on a single machine it is straightforward to setup additional machines that backup using the same account. The main utility of this is to obtain the benefit of doing realm deduplication, wherein multiple machines can share a pool of chunks and receive the corresponding space savings from this process.

Totaly great!

> 1. copy the contents of /etc/cyphertite from host1 to the new machine, host2. this can be done a number of ways, one example is

What is that we have to replicate on host n.2? I don't get the `/etc/cyphertite` part, which I do not have on the machine with Cyphertite installed and running btw.

**Comment by SirHumphreyAppleby** [comment]
I believe the only file you need is ~/.cyphertite/cyphertite.conf

**Comment by tukoz** [comment]
That's also how I understand.
Now atm the wiki makes things unclear, saying one should `copy the contents of /etc/cyphertite from host1 to the new machine, host2.`, and `We recommend saving cyphertite.conf and ct_crypto in a safe offline location.`
