### ISSUE TITLE
autoupdater for windows and osx

### ISSUE THREAD

**Issue by csmiken** [conformal/cyphertite#11]
When we enter a period of heavy development on the windows and osx gui, we will likely have a release every 1-2 weeks for a period of time. it is not very user-friendly to require updates to be installed manually, especially when there is so much churn.

taking a page from chrome and including an autoupdater will go a long ways to ease the updating process for users.

**Comment by kesh00** [comment]
But also impose some security risks. Please make sure that it's not mandatory!

**Comment by csmiken** [comment]
We added an auto-update check to Cyphertite 2.0.0 and higher. This check will notify you when an update is available and links you to a download for the latest version. You still need to go through Windows UAC and the installer process to alleviate the security concerns mentioned above.

We have not yet released a Mac GUI, but a similar approach will be released for Mac in the future.
