### ISSUE TITLE
be able to “launch right now” a backup which is scheduled for some time in the future

### ISSUE THREAD

**Issue by csmiken** [conformal/cyphertite#14]
At present, the only way to accomplish this is to wait until the scheduled date and time, or create a duplicate of said backup and set as a one time backup.

**Comment by l-a-r** [comment]
Seconded.
I signed up, painstakingly created a backup set, and set the job to run daily. Then I found out I couldn't set the job to run right now, as well.
As for "duplicate of said backup", I'd love to, but can't find any doc on the wiki. . . .

**Comment by csmiken** [comment]
This was added in Cyphertite 2.0.1
