### ISSUE TITLE
ctctl cull taking forever

### ISSUE THREAD

**Issue by schoelle** [conformal/cyphertite#48]
I have a repository with roughly daily 5500 backups, created from 13 different backup locations. I confess that this is large, and I had forgotten to setup 'ctctl cull' for it. Now I have started it, but it is running for 2.4 days in a row, and I still see no progress of old backups going away. How long can I expect it to run?

**Comment by csmiken** [comment]
Spoke with user, we discussed some best practices and when followed, cull worked as intended. He also updated to 1.6.5
