### ISSUE TITLE
question: can cyphertite be pointed at a self-hosted archive for backups?

### ISSUE THREAD

**Issue by iluminite** [conformal/cyphertite#53]
Hello,

Apologies if this question is answered in the FAQ, another issue, or somewhere in the examples/config/etc - I have poked around each of these but have not found my answer.

If I would like to host my backups myself, can cyphertite be configured to do so? If so, where might I find these configuration details?

thanks!

**Comment by csmiken** [comment]
At this time, Cyphertite does not support sending backups to a local device.

**Comment by iluminite** [comment]
@csmiken - does Cyphertite support sending backups to a hosted store I control, or can Cyphertite _only_ upload to the commercial Cyphertite backend?

**Comment by csmiken** [comment]
That is a better way to put it. The client will only send data to our commercial backend at this time. We have discussed some options to interface with a local device, or a customer managed black box to store the data, but I cannot tell you when or if it will be available.

**Comment by iluminite** [comment]
ok, thank you for confirming @csmiken. being able to store my data on own hardware would be a desirable setup for me.

**Comment by csmiken** [comment]
Understood. We have had a few requests for this and to be honest, we have it on the road map. It is also worth mentioning that we are focusing on some bitcoin projects presently so like I said before, I can't promise when we might get to that - but we know we would like it when we have the dev time to spend on it!

**Comment by iluminite** [comment]
@csmiken,

thanks for the reply. while your choice of licensing is obviously yours.. it would be more possible for that development to happen (spontaneously or not), if cyphertite's backend/server/storage/etc were part of the open source package.

It would also give us more confidence in the product.
