### ISSUE TITLE
Install from git script fails with "event_core" error on PCBSD 9.2-release system

### ISSUE THREAD

**Issue by sysfu** [conformal/cyphertite#60]
Running the install from git script on PCBSD fails with an error regarding not being able to find "event_core"

The fix is to modify line 79 of the ct_git_install.sh script so that it includes an additional path;

line 78 | # standard lib dirs - override below if needed
line 79 | SLIB_DIRS="/usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64 **/usr/local/lib/event2**"

Thanks to Mike from Conformal support for finding a quick solution to this issue.

**Comment by dajohi** [comment]
fix in git
