### ISSUE TITLE
Can't modify scheduled backup?

### ISSUE THREAD

**Issue by l-a-r** [conformal/cyphertite#75]
I'm using the Windows GUI, here.

I've created a daily scheduled backup. Now I realize I want to add one more folder to that backup. So far as I can tell, this means creating a **new** scheduled backup, and re-creating the backup set from scratch.

I hope this isn't true, because that's no kind of user interface. (And that probably comes across as harsh, but really I _like_ Cyphertite.)  (And also, the new Windows Cyphertite 2.0 is _miles_ ahead of the old one in ease of use, so applause there.)

Anyway, I feel that basic functionality (based on similar products and similar tasks) should include the ability to:
- Modify an existing scheduled backup (change the files/folders, or change the schedule);
- Duplicate an existing scheduled backup (to then modify it, and have both).
- Have a scheduled backup that isn't currently active, but which I can turn back on some day.

One suggestion: have some people who _aren't_ developers use some of the competition for a while -- Mozy, Carbonite, IDrive, Crashplan, etc. -- and keep track of what tasks they want to be able to do, and the good and bad aspects of using those tools. Then steal all the good UI features for Cyphertite

A more general comment is that I like Cyphertite, but it feels too much like it was created by developers for developers. Which is okay unless you want other users too. (Note: using Github to solicit feedback on desired features? That's another by-developers-for-developers thing.)

Thanks for your attention,

**Comment by l-a-r** [comment]
(Also just noticed that some of this duplicates issues #12, #13, #14, #15, #72. So I agree with them.)

**Comment by csmiken** [comment]
The ability to edit a scheduled backup has been added to Cyphertite 2.0.1.
