### ISSUE TITLE
Add option to configure temporary directory or incrementally move files to the final destination.

### ISSUE THREAD

**Issue by alphaleonis** [conformal/cyphertite#76]
When restoring a large backup set (on Windows) it seems that the entire backup set is written to a temporary folder first, instead of the destination folder I chose to extract to. In my situation this leads to the restore failing due to the disk space on my system drive being depleted during the restore. 

Is there some way to configure the temporary folder used by Cyphertite? If not, this should be added, possibly along with an option to move each file to the final destion directory as soon as it has been downloaded instead of waiting for the entire backup set to be downloaded.

**Comment by csmiken** [comment]
We have added this as an experimental feature in Cyphertite 2.0.1.  This means we added a setting, but do not yet have a UI means of editing the setting.

1) Open Regedit
2) Browse to "HKCU\Software\Conformal Systems\Cyphertite\Settings"
3) Create a new REG_SZ value called "Extract_TempPath".
4) Set the value to any existing directory, which will now be used for extract (such as "D:\CTTemp").

We plan to add this to our Settings page in a future release, but the functionality has been fully tested to use the alternate path for the temporary unpacking of files during extract operations.
