### ISSUE TITLE
cyphertitectl: error while loading shared libraries: libassl.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ghost** [conformal/cyphertite#82]
I'm running Trisquel 6.0.1, which is based on Ubuntu 12.04 LTS. Kernel version 3.11.0-20-generic. That is a later version of the kernel, to which I upgraded to improve performance.

~$ lsb_release -a
No LSB modules are available.
Distributor ID: Trisquel
Description:    Trisquel 6.0.1
Release:    6.0.1
Codename:   toutatis
~$ uname -r
3.11.0-20-generic

I decided to compile the source. I installed the dependencies.

sudo apt-get install gcc libbsd-dev libcurl4-openssl-dev libedit-dev libevent-dev libexpat-dev libz-dev liblzma-dev liblzo2-dev libsqlite3-dev

Then compiled, as described in the wiki. Looked good.

However, when I did "cyphertitectl config generate" I got this error: 

cyphertitectl: error while loading shared libraries: libassl.so.6: cannot open shared object file: No such file or directory

Is it me or a bug? (How should I fix it?)

**Comment by schmitmd** [comment]
You ought to do an ldd on the cyphertite binary you made. It will tell you which shared libraries it's linking to and where. I expect you just need a symlink in the right place to point at the intended file. The shared object file you're looking for will most likely be at /usr/lib/libassl.so.6  Good luck!

**Comment by ghost** [comment]
So it was me then! This is over my head, so I'll need to study more before I can make this work. Thanks for the help!
