### ISSUE TITLE
Incorrect "Account has run out of space" error

### ISSUE THREAD

**Issue by schmitmd** [conformal/cyphertite#90]
On some long-running backups, I've run into the following error:
chunk write failed: Account has run out of space - Please log in to your cyphertite.com account or contact support@cyphertite.com

This happens despite the fact that I have the Unlimited plan and occurs regardless of time since last renewal date.  Please fix.

**Comment by schmitmd** [comment]
Is anyone on this?  Very frustrating.

**Comment by csmiken** [comment]
We had a server issue which incorrectly reported an error to Cyphertite saying it was out of space. We have resolved this issue and are looking into ensuring it does not occur again.
If you re-start your backup at this time, it should complete properly.

**Comment by schmitmd** [comment]
Still having issues.  It's stopped 4 different simultaneous backups.  I've tried remote and local ctfile mode to no avail.  Is there any way I can be helpful in solving this issue?

**Comment by csmiken** [comment]
We completed part of the fix this morning. We still have a bit more work to do, which will likely include a client side software update to completely eliminate the issue. As of right now, you should be able to re-start your backups and have them complete normally. If you would like to provide your username via support@cyphertite.com I can take a look and make sure there is nothing else strange with your account.

**Comment by schmitmd** [comment]
Fixed for me as far as I can tell. Thanks! Feel free to close this issue whenever.
