### ISSUE TITLE
 Incorrect "Account has run out of space" error

### ISSUE THREAD

**Issue by schmitmd** [conformal/cyphertite#91]
This issue seems to have popped back up.

**Comment by csmiken** [comment]
We did have the same issue over the weeekend. I have my developer working on the release that should fix the incorrect error message now.

**Comment by schmitmd** [comment]
Any update on this?  Still seeing the error.

**Comment by csmiken** [comment]
We have an update release in the testing phase right now. It should be released soon if no issues are found during testing. Thank you for your patience.

**Comment by schmitmd** [comment]
This appears to have been resolved again.
