### ISSUE TITLE
Support Mac compilation

### ISSUE THREAD

**Issue by Thinkscape** [conformal/cyphertite#96]
I'd love to use cypherite, but it seems that there is no mac gui app.

However, I have nothing against compiling and using a CLI or fuse version, as long as you helped me with that. 

It seems that all dependencies are already compilable on OSX. How about writing a [homebrew keg](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook) that would do just that ?

**Comment by jcvernaleo** [comment]
@Thinkscape 

There is actually a homebrew formula for cypheretite.  It is not by conformal, but I worked with the guy who did it so any of the necessary patches are in cypheretite already.

https://github.com/Bluerise/homebrew-cyphertite

If you have any trouble getting that to work, please let me know.  I personally prefer macports to homebrew, but haven't gotten around to submitting a macports version of ct and I know this homebrew one works.
