### ISSUE TITLE
How to deal with 'failed to initialise cyphertite: Failed to connect'

### ISSUE THREAD

**Issue by tukoz** [conformal/cyphertite#97]
Have been unable to list or use cyphertite for some days now, with the message:

> failed to initialise cyphertite: Failed to connect
- Both backups, list with '-mt' and restore worked without a glitch first.
- I didn't touch the configuration file before it started to fail; I did change a couple of options after, though.
- Linux x86_64

At the moment I have no idea when did the last backup happened. 
Please how to be notified:
1. when a backup failed (whatever the reason eg _logs_)?
2. to display when the last backup occurred? 

Refs: Found one, which returned to normal within a day: 
https://github.com/conformal/cyphertite/issues/95

**Comment by alphaleonis** [comment]
I currently have the same problem. And it has occurred a couple of times before, but it seems to go back to normal within a couple of days.

**Comment by SirHumphreyAppleby** [comment]
Re Issue #95 which I posted, I'm not sure what the downtime was because I was only trialing the service, not running regular backups. The current issue has been unresolved for much longer.

Some scripting would be required to do what you want to achieve, and some of the exit codes of the application could probably do with tidying up (based on earlier comments about the software). If Cyphertite had worked for me (while I've been testing, it has been far too slow and unreliable), I had planned to use a small tool to compare directories every 15 minutes during the day (less frequently over night), and run a backup only when changes occurred. The -mt option will show you when the last backup occurred.

**Comment by schmitmd** [comment]
Plus one for broken accessibility. Discouraging for paying customers.

**Comment by artosan** [comment]
I'm facing the same problem. I keep getting "unable to connect to server: Failed to connect" when i try to run cyphertitectl config generate and punch in my credentials. I lost connection during backup (couple of days ago) and i have not been able to access remote ever since.

**Comment by andrewmeyer** [comment]
same issue here using Windows GUI on two machines.  logging in via the website works correctly though.

**Comment by tukoz** [comment]
@SirHumphreyAppleby thank you for sharing. Now simple _logs_ would help, wouldn't it? Better yet than `-mt` which returns no info but the _Failed to connect_ message.

btw have been unable to connect to cyphertite's vault for six days now. Ends up almost immediately on (with -D debugstring):

``` bash
0.003207: < ctutil.c ct_config_parse 322 > loaded config from /home/USER/.cyphertite/cyphertite.conf
0.189073: < ct_main.c ct_main 441 > failed to initialise cyphertite: Failed to connect
```

**Comment by SirHumphreyAppleby** [comment]
@lliseil. Sorry, I was looking at your question from the point of view of how to determine when the last backup was, assuming things were operating normally. If you are backing up a file system which records last access times, you could look for file access times which are close together, or at files you know nothing else would have opened.

Given six days of downtime, no comments from cyphertite on this ticket, and no response to support requests, I think knowing when backups last occurred is academic. I wouldn't assume you are going to be able to recover the data if you needed to.

**Comment by alphaleonis** [comment]
Now I am actually able to connect to the servers again. The last successful backup that ran was on the 26th, and since then I have gotten errors every other day (backup scheduled to run every other day) until now (december 1st)

**Comment by artosan** [comment]
It begun to work for me too. Would be nice to know it here is going to be more problems like this in the future.

**Comment by csmiken** [comment]
Sorry for the late response guys. We have had a server issue that denied connections for some of our users over the Thanksgiving holiday weekend. We are working the issue and doing some simultaneous upgrades to ensure that this does not happen again. We hope to have this resolved very soon for all users affected. We appreciate your patronage.

**Comment by csmiken** [comment]
I can confirm that as of now, the issue has been resolved for all users. We took the opportunity to preform some upgrades to the servers as stated above which added a small amount of time to the fix. Because of these upgrades, we are confident that the connection issue will not return.

**Comment by tukoz** [comment]
cyphertite ie backups and so on back to normal in this location, since Dec 2 0:00.
Thanks to csmiken for the work and updating us. I did not understand what caused the five days blackout, though.

**Comment by csmiken** [comment]
The blackout was caused by an issue on our connection servers. This is not the same device that houses user data. While we were working the connection issue, we took some time to upgrade the server to help ensure this would not happen again. That is all I can share publicly.

**Comment by tukoz** [comment]
Thanks csmiken
I'd like to aknowledge that processes have runned fine ever since you worked on that issue and upgraded the connection server.
